### ISSUE TITLE
Missing ping/pong functionality

### ISSUE THREAD

**Issue by getee** [sitegui/nodejs-websocket#17]
There is no support for websocket.ping() and websocket.on('pong'); as described in https://tools.ietf.org/html/rfc6455#section-5.5.2

I will upload later a fix for this.

**Comment by sitegui** [comment]
Hi @getee ,

There is support for ping/pong frames as specified in the spec ([implemented here](https://github.com/sitegui/nodejs-websocket/blob/649b41a6c75c92f8607512e299b985bed6e9c5f5/Connection.js#L483-L492)), but there is no public API for that.

There is one way of sending a PING frame with no data right now and a hint if you want to contribute this ;)
```js
var frame = require('nodejs-websocket/frame')

function sendPing(connection) {
    connection.socket.write(frame.createPingFrame(!connection.server))
}
```

The suggested public API seems good. My suggestion is to let `websocket.ping()` receive the optional payload (string or buffer) and the `'pong'` event emit the received payload.

Feel free to PR on this and ask for any help you need.

**Comment by getee** [comment]
yeah when I went through the code I saw these frames. I have implemented the ping() and indeed an event pong on receival.

I have sent you a pull request with this implementation. I had to implement the ping/pong functionality today so why not share it ;)
