### ISSUE TITLE
Client IP address?

### ISSUE THREAD

**Issue by scripting** [sitegui/nodejs-websocket#21]
Is there a way to get the IP address of the client from the *connection* object? 

Thanks in advance. I'm using this package as the server component for updates for scripting.com. It's working really well. Thank you.

**Comment by sitegui** [comment]
Hello @scripting

Yes: `conn.socket.remoteAddress`. See the docs on [Connection#socket](https://github.com/sitegui/nodejs-websocket#connectionsocket) and [Socket#remoteAddress](https://nodejs.org/api/net.html#net_socket_remoteaddress)

You're welcome ;)

(I'll close this, if this doesn't work for you, feel free to reopen)

**Comment by scripting** [comment]
Thanks, this worked. ;-)
