### ISSUE TITLE
WS on sencha connect

### ISSUE THREAD

**Issue by rumkin** [sitegui/nodejs-websocket#3]
Is it possible to integrate nodejs-websocket with connect (or express) https server to run on the same port?

**Comment by rndmania** [comment]
i have changed some part of your example.

// "sec-websocket-accept" -> "sec-websocket-key"
function recreateWSHandshake(req) {
    return "GET "+req.url+" HTTP/1.1\r\n"+
        "Host: "+req.headers.host+"\r\n"+
        "Upgrade: websocket\r\n"+
        "Connection: Upgrade\r\n"+
        "Sec-WebSocket-Key: "+req.headers["sec-websocket-key"]+"\r\n"+
        "Sec-WebSocket-Version: 13\r\n\r\n"
}

// 'server' is 'http' module`s instance can used with express
 server.on('upgrade', function(req, socket, head) {
          var client = net.connect({port: 4000}, function () {
               // Send the handshake again (see bellow)
                client.write(recreateWSHandshake(req))
                // Proxy
                client.pipe(req.socket)
                req.socket.pipe(client)
          });
          socket.once('close', function(e) {
                client.destroy();
          });
});

It works well. but this approach needs so many ports
