### ISSUE TITLE
not clear on how server can receive binary from client

### ISSUE THREAD

**Issue by scottstensland** [sitegui/nodejs-websocket#4]
I would like to use your library to allow my browser client side to send to node-js server side binary data in form of a typed array such as Uint8Array.  I am successfully sending normal text from client to server.  When attemping binary, here is my client side send 

socket.binaryType = 'arraybuffer';
socket.send(big_monster_data);

and here is my nodejs-websocket server side which is NOT correctly receiving the client sent data 

var server = ws.createServer(function (connection_request) {

```
// here is text which is received just fine
connection_request.on("text", function (received_data) {
        console.log("Received text format : " + received_data);
        connection_request.sendText(received_data.toUpperCase()+" OK");
    });

// here is attempt at binary which is not working
connection_request.on("binary", function (received_data) {

// below gets printed YET length is undefined
console.log("Received binary format of length ", received_data.length);

    if (received_data instanceof ArrayBuffer) {

        // this is NOT getting reached
        console.log("OK instanceof ArrayBuffer");
    }

    // HERE I want to do something with received arraybuffer
}
```

}

thank you for your time

cheers, Scott Stensland

**Comment by nazar-pc** [comment]
@sitegui, I'd add this to readme, since I'm working with JS every day, but not with Node.js and having need for very simple WebSockets server it was not clear for me how to get binary data as well.

**Comment by sitegui** [comment]
Hi @nazar-pc, that's a valid point.

I'm open to a pull request if you like, otherwise I can manage to do this by the middle of the week.

Cheers
