### ISSUE TITLE
Nagle's Algorithm in nodejs-websocket ?

### ISSUE THREAD

**Issue by Logstone** [sitegui/nodejs-websocket#42]
Not really an issue, just a question.
Does nodejs-websocket make use of Nagle's Algorithm?
If so, how do I turn it off?

**Comment by sitegui** [comment]
Hello @Logstone 

This module uses Node.js' core socket implementation. You can access the underlying socket object via the [`socket` property](https://github.com/sitegui/nodejs-websocket#connectionsocket)

From Node docs:
> By default TCP connections use the Nagle algorithm

So yes, websockets created with this lib have Nagle's algorithm on by default. You can change that via [socket.setNoDelay([noDelay])](https://nodejs.org/dist/latest-v7.x/docs/api/net.html#net_socket_setnodelay_nodelay)
