### ISSUE TITLE
Keep Alive?

### ISSUE THREAD

**Issue by dannysmc95** [sitegui/nodejs-websocket#44]
Hi there,

I am currently using this for a work project, I am struggling to see why I keep getting this issue:
'This socket has been ended by the other party', I assume it needs some kind of keep alive? or is this already included with this?

Thanks,
Danny

**Comment by BadOPCode** [comment]
How long are you connected before it drops the socket.   A lot of routers (most) will drop idle sockets after a couple of minutes.  You can either send a keep alive or if you want to keep it slimmer you can check for the close event and just reconnect if it's not closing for a good reason.  :)

**Comment by dannysmc95** [comment]
Thanks @BadOPCode that's not a bad shout! When you say keep alive, I thought this library had a keep alive? Apparently you can set it in the websocket server connection scope.

**Comment by sitegui** [comment]
Hi @dannysmc95 , you're right, this lib does not change the default Node's keepAlive.

However you can use socket API to change that: [`socket.setKeepAlive(true)`](https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay)
