### ISSUE TITLE
Get Connection IP

### ISSUE THREAD

**Issue by theiajsanchez** [sitegui/nodejs-websocket#48]
Hi,

I can't find a way in which I can get the ipv4 address of a new connection.

Is there a way for doing this?

Thanks in advance

**Comment by padjon** [comment]
connection.socket.remoteAddress
did it for me

**Comment by sitegui** [comment]
That's right, `connection.socket` exposes a node's net.Socket instance: https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_socket_remoteaddress
