### ISSUE TITLE
Publish release 1.7.2 to npm repository

### ISSUE THREAD

**Issue by hlovdal** [sitegui/nodejs-websocket#55]
Release [1.7.2](https://github.com/sitegui/nodejs-websocket/releases/tag/v1.7.2) includes a fix for [issue 46](https://github.com/sitegui/nodejs-websocket/pull/46), however it is not published to [the npm repository](https://www.npmjs.com/package/nodejs-websocket). Could you do that?

**Comment by sitegui** [comment]
Ops, sorry about that :P

That should be done now
